backend:
  name: github
  repo: TongHuaLabs/tham-website
  branch: main
  base_url: http://188.166.221.158

local_backend: false # Enables Netlify CMS locally
media_folder: src/images
public_folder: ../../../images

collections:
  # News TH
  - name: 'news_TH'
    label: 'News TH'
    folder: 'src/markdown/news/th'
    create: true
    slug: '{{title}}'
    fields:
      - {
          label: 'Category',
          name: 'category',
          widget: 'hidden',
          default: 'news',
        }
      - { label: 'Lang', name: 'lang', widget: 'hidden', default: 'th' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Slug',
          name: 'slug',
          widget: 'string',
          hint: 'must be replace whitespace with -',
        }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'date',
          date_format: 'YYYY-MM-DD',
        }
      - {
          label: 'Feature Image',
          name: 'cover',
          widget: image,
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  # News EN
  - name: 'news_EN'
    label: 'News EN'
    folder: 'src/markdown/news/en'
    create: true
    slug: '{{title}}'
    fields:
      - {
          label: 'Category',
          name: 'category',
          widget: 'hidden',
          default: 'news',
        }
      - { label: 'Lang', name: 'lang', widget: 'hidden', default: 'en' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Slug',
          name: 'slug',
          widget: 'string',
          hint: 'must be replace whitespace with -',
        }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'date',
          date_format: 'YYYY-MM-DD',
        }
      - {
          label: 'Feature Image',
          name: 'cover',
          widget: image,
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  # Branches EN
  - name: 'branches_EN'
    label: 'Branches EN'
    folder: 'src/markdown/braches/en'
    create: true
    slug: '{{title}}'
    fields:
      - { label: 'Category', name: 'category', widget: 'hidden', default: 'oa' }
      - { label: 'Lang', name: 'lang', widget: 'hidden', default: 'en' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Address', name: 'address', widget: 'string' }
      - { label: 'Email', name: 'email', widget: 'string' }
      - { label: 'Code', name: 'code', hint: 'Example: 01', widget: 'string' }
      - {
          label: 'Tel Display',
          name: 'tel_display',
          hint: 'Example: (+66) 2236-0171-6',
          widget: 'string',
        }
      - {
          label: 'Tel To',
          name: 'tel',
          hint: 'Example: +66223601716',
          widget: 'string',
        }
      - {
          label: 'Line ID',
          name: 'line_display',
          hint: 'Example: @thamc',
          widget: 'string',
        }
      - {
          label: 'Line URL',
          name: 'line_url',
          hint: 'Example: https://www.google.com',
          widget: 'string',
        }

  # Branches TH
  - name: 'branches_TH'
    label: 'Branches TH'
    folder: 'src/markdown/braches/th'
    create: true
    slug: '{{title}}'
    fields:
      - { label: 'Category', name: 'category', widget: 'hidden', default: 'oa' }
      - { label: 'Lang', name: 'lang', widget: 'hidden', default: 'th' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Address', name: 'address', widget: 'string' }
      - { label: 'Email', name: 'email', widget: 'string' }
      - { label: 'Code', name: 'code', hint: 'Example: 01', widget: 'string' }
      - {
          label: 'Tel Display',
          name: 'tel_display',
          hint: 'Example: (+66) 2236-0171-6',
          widget: 'string',
        }
      - {
          label: 'Tel To',
          name: 'tel',
          hint: 'Example: +66223601716',
          widget: 'string',
        }
      - {
          label: 'Line ID',
          name: 'line_display',
          hint: 'Example: @thamc',
          widget: 'string',
        }
      - {
          label: 'Line URL',
          name: 'line_url',
          hint: 'Example: https://www.google.com',
          widget: 'string',
        }
