backend:
  name: git-gateway
  branch: main # Change to your production branch

local_backend: true # Enables Netlify CMS locally
media_folder: src/images
public_folder: ../../../images

collections:
  # News TH
  - name: 'news_TH'
    label: 'News TH'
    folder: 'src/markdown/news/th'
    create: true
    slug: '{{title}}'
    fields:
      - {
          label: 'Category',
          name: 'category',
          widget: 'hidden',
          default: '/news/blog/',
        }
      - { label: 'Lang', name: 'lang', widget: 'hidden', default: 'th' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Slug',
          name: 'slug',
          widget: 'string',
          hint: 'must be replace whitespace with -',
        }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'date',
          date_format: 'YYYY-MM-DD',
        }
      - {
          label: 'Feature Image',
          name: 'cover',
          widget: image,
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  # News EN
  - name: 'news_EN'
    label: 'News EN'
    folder: 'src/markdown/news/en'
    create: true
    slug: '{{title}}'
    fields:
      - {
          label: 'Category',
          name: 'category',
          widget: 'hidden',
          default: '/news/blog/',
        }
      - { label: 'Lang', name: 'lang', widget: 'hidden', default: 'en' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Slug',
          name: 'slug',
          widget: 'string',
          hint: 'must be replace whitespace with -',
        }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'date',
          date_format: 'YYYY-MM-DD',
        }
      - {
          label: 'Feature Image',
          name: 'cover',
          widget: image,
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
